FROM apache/superset:latest

USER root

RUN /app/.venv/bin/python -m ensurepip \
    && /app/.venv/bin/python -m pip install --upgrade pip setuptools wheel

RUN /app/.venv/bin/python -m pip install \
        "SQLAlchemy<2" \
        "clickhouse-connect>=0.13.0" \
        "psycopg2-binary"

USER superset