FROM jupyter/pyspark-notebook:latest

USER root

# Python dependencies
COPY requirements.txt /tmp/requirements.txt
RUN pip install --default-timeout=1000 --no-cache-dir -r /tmp/requirements.txt

# Java 11
RUN wget https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_x64_linux_hotspot_11.0.20.1_1.tar.gz && \
    mkdir -p /opt/java/openjdk11 && \
    tar -xzf OpenJDK11U-jdk_x64_linux_hotspot_11.0.20.1_1.tar.gz \
        -C /opt/java/openjdk11 \
        --strip-components=1 && \
    rm OpenJDK11U-jdk_x64_linux_hotspot_11.0.20.1_1.tar.gz

# JARs for MinIO / S3A
COPY ./spark/jars /usr/local/spark/jars/

# Persistent Spark configuration
COPY ./spark/conf/spark-defaults.conf /usr/local/spark/conf/spark-defaults.conf

# Java
ENV JAVA_HOME=/opt/java/openjdk11
ENV PATH=$JAVA_HOME/bin:$PATH

USER jovyan

HEALTHCHECK NONE